export const LAY_THONG_TIN_NGUOI_DUNG  = 'LAY_THONG_TIN_NGUOI_DUNG'
export const LAY_DANH_SACH_NGUOI_DUNG  = 'LAY_DANH_SACH_NGUOI_DUNG'
export const TIM_KIEM_NGUOI_DUNG = "TIM_KIEM_NGUOI_DUNG"
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CHON_NGUOI_DUNG = "CHON_NGUOI_DUNG";